version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/amd64
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel

    webserver:
        image: nginx:1.27
        container_name: nginx_server
        platform: linux/amd64
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3310:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
